package dsa;

import java.util.Arrays;

public class LeetCode389 {

    //389. Find the Difference

    /*You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.*/

    public static char findTheDifference(String s, String t) {
        char[] sArr = s.toCharArray();
        char[] tArr = t.toCharArray();
        int size1 = 0;
        int size2 = t.charAt(t.length()-1);
        for (int i=0; i<s.length(); i++) {
            size1 += sArr[i];
            size2 += tArr[i];
        }
        return  (char) (size2 - size1);
    }

    public static void main(String[] args) {

        /*Example 1:
        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.*/

        System.out.println(findTheDifference("abcd","abcde"));

        /*Example 2:
        Input: s = "", t = "y"
        Output: "y"*/

        System.out.println(findTheDifference("","y"));
    }

}
